apiVersion: v1
kind: Namespace
metadata:
  name: ongi
---
apiVersion: v1
kind: Namespace
metadata:
  name: ongi-obs
---
  # ------------------------------------------------------------
  # 로컬 JVM(호스트)로 프록시용 Service (k3d: host.k3d.internal)
  # - 스프링부트가 로컬 8080에서 떠있을 때 Ingress가 이 서비스로 보냅니다.
  # ------------------------------------------------------------
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: ongi-app
#  namespace: ongi
#spec:
#  type: ExternalName
#  externalName: host.k3d.internal
#  ports:
#    - name: http
#      port: 8080
#
## ------------------------------------------------------------
## Ingress들
## ------------------------------------------------------------
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ongi-app-ing
#  namespace: ongi
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: ongi.ongi.local
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: ongi-app
#                port:
#                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ing
  namespace: ongi-obs
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.ongi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ing
  namespace: ongi-obs
spec:
  ingressClassName: nginx
  rules:
    - host: prometheus.ongi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090