[versions]
querydsl   = "5.1.0"
mysql      = "9.3.0"
log4jdbc   = "1.2"
log4j-api  = "2.17.0"
jjwt       = "0.11.5"
spark      = "4.0.0"
h2         = "2.3.232"

[libraries]
querydsl-core        = { module = "com.querydsl:querydsl-core",              version.ref = "querydsl"  }
querydsl-sql         = { module = "com.querydsl:querydsl-sql",               version.ref = "querydsl"  }
querydsl-sql-spring  = { module = "com.querydsl:querydsl-sql-spring",        version.ref = "querydsl"  }

mysql-connector      = { module = "com.mysql:mysql-connector-j",             version.ref = "mysql"     }

log4jdbc             = { module = "com.googlecode.log4jdbc:log4jdbc",        version.ref = "log4jdbc"  }
log4j-api            = { module = "org.apache.logging.log4j:log4j-api",      version.ref = "log4j-api" }

jjwt-api             = { module = "io.jsonwebtoken:jjwt-api",                version.ref = "jjwt"      }
jjwt-impl            = { module = "io.jsonwebtoken:jjwt-impl",               version.ref = "jjwt"      }
jjwt-jackson         = { module = "io.jsonwebtoken:jjwt-jackson",            version.ref = "jjwt"      }

spark-sql            = { module = "org.apache.spark:spark-sql_2.13",         version.ref = "spark"     }
spark-sql-kafka      = { module = "org.apache.spark:spark-sql-kafka-0-10_2.13", version.ref = "spark"     }
h2-database          = { module = "com.h2database:h2",                       version.ref = "h2"        }