# local 환경
spring:
  application:
    name: ongi
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/ongi?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: tmdals285!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4
      leak-detection-threshold: 30000
      maximum-pool-size: 10 # 커넥션 수 조정 필요할 때 명시
      minimum-idle: 5 # 유휴 커넥션 수 조정 시 사용
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false
  security:
    jwt:
      issuer: "ongi"
      access-exp-seconds: 90 # 15분
      refresh-exp-seconds: 1209600 # 14일
      access-key: snO+mXp9+ONXBHwX6D8EqsXq38PUaqJuspmkeK+nY+LWRBubp/+OwzlZ2+Tl3zzC
      refresh-key: ELKy9Qti74caVAWvuKHRWZ4ISZ+YBHfFAIqM3jin5GtaQmk0xlL/CgWZftX4UoTV
  data:
    redis:
      enabled: true
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 16      # 동시에 사용할 커넥션 최대 수
          max-idle: 8
          min-idle: 1
          max-wait: 2000ms
  health:
    redis:
      enabled: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      batch-size: 65536        # 64KB
      linger-ms: 10            # 소량 트래픽이면 5~10ms 정도로 batch 효과
      buffer-memory: 33554432  # 32MB
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        retries: 2147483647
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
        compression.type: zstd
      #transaction-id-prefix: ongi-tx-
    consumer:
      bootstrap-servers: localhost:9092
      group-id: user-stats-updater
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false  # 수동 커밋 추천 (성능·정합성 제어 용이)
    listener:
      type: single
      ack-mode: manual           # 수동 ack (enable-auto-commit=false와 맞춰서)
  outbox:
    publisher:
      fixed-delay-ms: 30000
#logging:
#  level:
#    io.opentelemetry: DEBUG        # OTel SDK/Export
#    io.micrometer: DEBUG           # Micrometer(OTLP 레지스트리)
#    com.github.loki4j: DEBUG
#management:
#  metrics:
#    tags:
#      app: ${spring.application.name}
#      service_name: ${spring.application.name}
#      env: ${spring.profiles.active:local}
#  tracing:
#    sampling:
#      probability: 1.0
#  otlp:
#    tracing:
#      endpoint: http://43.201.71.69:14318/v1/traces
#      resource-attributes:
#        deployment.environment: ${spring.profiles.active:local}
#    metrics:
#      export:
#        enabled: true
#        url: http://43.201.71.69:14318/v1/metrics